// ********RoostGPT********
// Test generated by RoostGPT for test react-test-tic-cli using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
/**
 * @jest-environment jsdom
 */

import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import Board from '../../src/components/board/Board';
import Square from '../../src/components/square/Square';

describe('Board', () => {
    test('ensures that clicking on a square calls the onClick callback', () => {
        const handler = jest.fn();
        const squares = Array(9).fill(null);
        const {getByText} = render(<Board squares={squares} onClick={handler} jumpTo={() => {}} />);

        const firstSquare = getByText('');
        fireEvent.click(firstSquare);
        expect(handler).toHaveBeenCalled();
    });

    test('renders all squares', () => {
        const squares = [null, null, null, 'X', 'O', 'X', null, null, null];
        const {getAllByText} = render(<Board squares={squares} onClick={() => {}} jumpTo={() => {}} />);

        expect(getAllByText('X').length).toBe(2);
        expect(getAllByText('O').length).toBe(1);
    });

    test('restart button calls jumpTo with 0', () => {
        const jumpTo = jest.fn();
        const {getByText} = render(<Board squares={Array(9).fill(null)} onClick={() => {}} jumpTo={jumpTo} />);

        const restartButton = getByText('Restart the game');
        fireEvent.click(restartButton);
        expect(jumpTo).toHaveBeenCalledWith(0);
    });
});

