// ********RoostGPT********
// Test generated by RoostGPT for test react-test-tic using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
import calculateWinner from '../../../src/helpers/calculateWinner.js';

describe('calculateWinner', () => {
  test('should return the winner if a winning combination is present on the first row', () => {
    const squares = ['X', 'X', 'X', null, null, null, null, null, null];
    expect(calculateWinner(squares)).toBe('X');
  });

  test('should return the winner if a winning combination is present diagonally from top-left to bottom-right', () => {
    const squares = ['O', null, null, null, 'O', null, null, null, 'O'];
    expect(calculateWinner(squares)).toBe('O');
  });

  test('should return null if there is no winner', () => {
    const squares = ['X', 'O', 'X', 'X', 'O', 'O', null, null, null];
    expect(calculateWinner(squares)).toBeNull();
  });

  test('should handle inputs where some squares are null (incomplete game)', () => {
    const squares = ['X', null, 'O', null, 'X', null, 'O', null, null];
    expect(calculateWinner(squares)).toBeNull();
  });
});

