// ********RoostGPT********
// Test generated by RoostGPT for test react-test-tic-cli using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import GameInfo from '../../../../src/components/game-info/GameInfo';

describe('GameInfo Component', () => {
    test('displays Player X\'s turn when no winner and xIsNext is true', () => {
        render(<GameInfo status="No Winner" winner={null} xIsNext={true} />);
        expect(screen.getByText("It's your turn, player X")).toBeInTheDocument();
    });

    test('displays Player O\'s turn when no winner and xIsNext is false', () => {
        render(<GameInfo status="No Winner" winner={null} xIsNext={false} />);
        expect(screen.getByText("Now you, player O!")).toBeInTheDocument();
    });

    test('displays winning message for Player X', () => {
        render(<GameInfo status="Winner: X" winner={true} xIsNext={false} />);
        expect(screen.getByText("Nice! I won!")).toBeInTheDocument();
    });

    test('displays winning message for Player O', () => {
        render(<GameInfo status="Winner: O" winner={true} xIsNext={true} />);
        expect(screen.getByText("Wohoo! I made Those')).toBeInTheDocument();
    });

    test('displays correct image alt text', () => {
        render(<GameInfo status="No Winner" winner={null} xIsNext={true} />);
        expect(screen.getByAltText("Player X and Player O")).toBeInTheDocument();
    });
});

