// ********RoostGPT********
// Test generated by RoostGPT for test tic-tac-toe using AI Type Open AI and AI Model gpt-4-turbo-preview



// ********RoostGPT********
// src/components/board/Board.js
import React from 'react';

const Board = ({ size, onSquareClick }) => {
  const renderSquares = () => {
    return [...Array(size)].map((_, idx) => (
      <button key={idx} data-testid={`square-${idx}`} onClick={() => onSquareClick(idx)}>
        Square {idx}
      </button>
    ));
  };

  return <div data-testid="board">{renderSquares()}</div>;
};

export default Board;
