// ********RoostGPT********
// Test generated by RoostGPT for test react-tic using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import calculateWinner from '../../../src/helpers/calculateWinner';

describe('calculateWinner', () => {
  test('should return the winner when a line is completed', () => {
    const squares = ['X', 'X', 'X', null, null, null, null, null, null];
    const winner = calculateWinner(squares);
    expect(winner).toBe('X');
  });

  test('should return null when there is no winner', () => {
    const squares = ['X', 'O', 'X', 'X', 'O', 'O', null, null, null];
    const winner = calculateWinner(squares);
    expect(winner).toBeNull();
  });

  // Additional test cases can be added to cover other scenarios, edge cases, and error handling
});

