// ********RoostGPT********
// Test generated by RoostGPT for test react-test-tic using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import Game from '../../index';

describe('Game component', () => {
  test('renders Tic Tac Toe title', () => {
    render(<Game />);
    expect(screen.getByText(/Tic Tac Toe/i)).toBeInTheDocument();
  });

  test('checks initial state without any winner', () => {
    render(<Game />);
    expect(screen.getByText('Next player: X')).toBeInTheDocument();
  });

  test('handles square click and updates state', () => {
    render(<Game />);
    const firstSquare = screen.getAllByRole('button')[0];
    fireEvent.click(firstSquare);
    expect(screen.getByText('Next player: O')).toBeInTheDocument();
  });

  test('determines a winner correctly', () => {
    render(<Game />);
    const buttons = screen.getAllByRole('button');
    fireEvent.click(buttons[0]); // X
    fireEvent.click(buttons[1]); // O
    fireEvent.click(buttons[4]); // X
    fireEvent.click(buttons[5]); // O
    fireEvent.click(buttons[8]); // X
    expect(screen.getByText('Winner: X')).toBeInTheDocument();
  });

  // Additional tests can include edge cases and error handling.
});

