// ********RoostGPT********
// Test generated by RoostGPT for test react-test-tic using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
// Importing the necessary utilities for React testing
import reportWebVitals from '../reportWebVitals.js';

describe('reportWebVitals', () => {
  // This function will mock the addEventListener on window object
  const setup = () => {
    const logSpy = jest.spyOn(console, 'log');
    global.performance = {
      mark: jest.fn(),
      measure: jest.fn()
    };
    return { logSpy };
  };

  test('should call console.log with report', () => {
    const { logSpy } = setup();
    const onPerfEntry = jest.fn((entry) => console.log(entry));
    reportWebVitals(onPerfEntry);

    expect(onPerfEntry).toHaveBeenCalled();
    expect(logSpy).toHaveBeenCalledWith(expect.any(Object));
  });

  test('should handle absence of performance.mark function gracefully', () => {
    global.performance.mark = undefined;  // Remove mark function to simulate error
    const onPerfEntry = jest.fn();
    reportWebVitals(onPerfEntry);

    expect(onPerfEntry).not.toHaveBeenCalled();
  });

  afterAll(() => {
    jest.restoreAllMocks();
  });
});

