// ********RoostGPT********
// Test generated by RoostGPT for test react-tic using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import Square from '../../components/square/Square.js';

describe('Square component', () => {
  test('renders the Square component with correct value', () => {
    const value = 'X';
    const { getByText } = render(<Square value={value} />);
    expect(getByText(value)).toBeInTheDocument();
  });

  test('calls the onClick callback when clicked', () => {
    const onClick = jest.fn();
    const { getByText } = render(<Square value="X" onClick={onClick} />);
    fireEvent.click(getByText('X'));
    expect(onClick).toHaveBeenCalled();
  });

  // Additional test cases could include:
  // - Testing the click event when no value is present (to simulate an empty square being clicked)
  // - Testing the component with different values (e.g., 'X', 'O', or null)
  // - Checking if the 'square' CSS class is applied correctly
  // - Error boundary tests, if the component interacts with other components or services that may fail
});

