// ********RoostGPT********
// Test generated by RoostGPT for test react-tic using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// src/ExampleComponent.js
import React from 'react';

function ExampleComponent({ title }) {
  return <h1>{title}</h1>;
}

export default ExampleComponent;

