// ********RoostGPT********
// Test generated by RoostGPT for test react-test-tic-cli using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Square from '../../../../src/components/square/Square';

describe('Square Component Tests', () => {
    test('Renders correctly with default props', () => {
        render(<Square />);
        const squareElement = screen.getByTestId('square-button');
        expect(squareElement).toBeInTheDocument();
    });

    test('Calls correct function on click', () => {
        const mockOnClick = jest.fn();
        render(<Square value="X" onClick={mockOnClick} />);
        const squareElement = screen.getByTestId('square-button');
        fireEvent.click(squareElement);
        expect(mockOnClick).toHaveBeenCalled();
    });

    test('Correctly displays the passed value', () => {
        const value = 'X';
        render(<Square value={value} />);
        const squareElement = screen.getByTestId('square-button');
        expect(squareElement.textContent).toBe(value);
    });
});

