// ********RoostGPT********
// Test generated by RoostGPT for test react-tic using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, fireEvent, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import Square from '../../../src/components/square/Square';

describe('Square component', () => {

  test('renders a button with the provided value', () => {
    const value = 'X';
    render(<Square value={value} onClick={() => {}} />);
    
    const button = screen.getByRole('button');
    expect(button).toHaveTextContent(value);
  });

  test('calls the onClick prop when clicked', () => {
    const onClick = jest.fn();
    render(<Square value="" onClick={onClick} />);
    
    const button = screen.getByRole('button');
    fireEvent.click(button);
    
    expect(onClick).toHaveBeenCalledTimes(1);
  });

});

